// Export progress data for therapist
window.ExportUtil = {
  generateReport(sessions, stats, language) {
    const isNL = language === 'nl';
    const now = new Date();
    const lines = [];

    lines.push('═'.repeat(50));
    lines.push(isNL ? '  WOORDSPEL - Voortgangsrapport' : '  WOORDSPEL - Progress Report');
    lines.push('═'.repeat(50));
    lines.push('');
    lines.push(`${isNL ? 'Datum' : 'Date'}: ${now.toLocaleDateString(language === 'nl' ? 'nl-NL' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
    lines.push('');

    // Overall stats
    lines.push(isNL ? '── Algemene Statistieken ──' : '── Overall Statistics ──');
    lines.push(`${isNL ? 'Totaal oefeningen' : 'Total exercises'}: ${stats.totalExercises}`);
    lines.push(`${isNL ? 'Totaal goed' : 'Total correct'}: ${stats.totalCorrect}`);
    const accuracy = stats.totalExercises > 0
      ? Math.round((stats.totalCorrect / stats.totalExercises) * 100)
      : 0;
    lines.push(`${isNL ? 'Nauwkeurigheid' : 'Accuracy'}: ${accuracy}%`);
    lines.push(`${isNL ? 'Beste reeks' : 'Best streak'}: ${stats.bestStreak}`);
    lines.push('');

    // Recent sessions
    if (sessions.length > 0) {
      lines.push(isNL ? '── Recente Sessies ──' : '── Recent Sessions ──');
      lines.push('');

      // Group by date
      const byDate = {};
      sessions.forEach(s => {
        const dateKey = new Date(s.date).toLocaleDateString(language === 'nl' ? 'nl-NL' : 'en-US');
        if (!byDate[dateKey]) byDate[dateKey] = [];
        byDate[dateKey].push(s);
      });

      const exerciseNames = {
        nl: { pictureNaming: 'Plaatje Benoemen', sentenceFill: 'Zin Aanvullen', wordRepeat: 'Woord Herhalen' },
        en: { pictureNaming: 'Picture Naming', sentenceFill: 'Sentence Fill', wordRepeat: 'Word Repeat' },
      };

      Object.entries(byDate).forEach(([date, daySessions]) => {
        lines.push(`📅 ${date}`);
        daySessions.forEach(s => {
          const name = (exerciseNames[language] || exerciseNames.en)[s.exerciseType] || s.exerciseType;
          const pct = Math.round((s.score / s.total) * 100);
          const diff = s.difficulty.charAt(0).toUpperCase() + s.difficulty.slice(1);
          lines.push(`   ${name} | ${s.score}/${s.total} (${pct}%) | ${diff}`);
        });
        lines.push('');
      });
    }

    // Difficulty progression
    if (sessions.length >= 3) {
      lines.push(isNL ? '── Moeilijkheidsverloop ──' : '── Difficulty Progression ──');
      const recent = sessions.slice(-10);
      const avgScore = recent.reduce((sum, s) => sum + (s.score / s.total), 0) / recent.length;
      lines.push(`${isNL ? 'Gemiddelde score (laatste 10)' : 'Average score (last 10)'}: ${Math.round(avgScore * 100)}%`);

      const difficulties = recent.map(s => s.difficulty);
      const lastDiff = difficulties[difficulties.length - 1];
      lines.push(`${isNL ? 'Huidig niveau' : 'Current level'}: ${lastDiff}`);
      lines.push('');
    }

    lines.push('─'.repeat(50));
    lines.push(isNL ? 'Gegenereerd door Woordspel' : 'Generated by Woordspel');
    lines.push('─'.repeat(50));

    return lines.join('\n');
  },

  downloadReport(sessions, stats, language) {
    const text = this.generateReport(sessions, stats, language);
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `woordspel-rapport-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  },

  shareReport(sessions, stats, language) {
    const text = this.generateReport(sessions, stats, language);
    if (navigator.share) {
      navigator.share({
        title: 'Woordspel Report',
        text: text,
      }).catch(() => {
        // Fallback to clipboard
        this.copyToClipboard(text);
      });
    } else {
      this.copyToClipboard(text);
    }
  },

  copyToClipboard(text) {
    navigator.clipboard.writeText(text).then(() => {
      alert('Rapport gekopieerd naar klembord! / Report copied to clipboard!');
    }).catch(() => {
      // Final fallback
      const ta = document.createElement('textarea');
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      alert('Rapport gekopieerd naar klembord! / Report copied to clipboard!');
    });
  },
};
